# Generated by Django 5.0.7 on 2024-08-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='metalData',
        ),
    ]
