# Generated by Django 5.0.7 on 2024-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_test_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetalStuff",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("data", models.JSONField()),
            ],
        ),
    ]
